"""users table extended 3

Revision ID: 08abd618ebd4
Revises: 81e075aea145
Create Date: 2023-04-12 02:54:21.065387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08abd618ebd4'
down_revision = '81e075aea145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
